# Change these first
owner: ASJordi # Your GitHub organization or username, where this repository lives
repo: website-activity-status # The name of this repository

sites:
  - name: Website
    url: https://asjordi.dev
    assignees:
      - ASJordi

  - name: Links
    url: https://links.asjordi.dev/
    assignees:
      - ASJordi

  - name: URL Shortener
    url: https://link-shortly.netlify.app
    assignees:
      - ASJordi

  - name: URL Shortener API
    url: https://url-short.up.railway.app
    assignees:
      - ASJordi

  - name: Weather App
    url: https://weather-app-nodejs.netlify.app
    assignees:
      - ASJordi

  - name: Weather App API
    url: https://weather-app-js.up.railway.app/api
    assignees:
      - ASJordi

  - name: API Words
    url: https://api-words.up.railway.app
    assignees:
      - ASJordi

status-website:
  name: Website Activity Status
  cname: up.asjordi.dev # Custom CNAME
  logoUrl: https://raw.githubusercontent.com/ASJordi/website-activity-status/master/assets/status.png
  favicon: https://raw.githubusercontent.com/ASJordi/website-activity-status/master/assets/status.png
  theme: night
  introMessage: Status page which uses real-time data from our GitHub repository. No server required — just GitHub Actions, Issues, and Pages.
  navbar:
    - title: Live Status
      href: https://asjordi.github.io/website-activity-status
    - title: GitHub Repo
      href: https://github.com/$OWNER/$REPO
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
