# Change these first
owner: ASJordi # Your GitHub organization or username, where this repository lives
repo: website-activity-status # The name of this repository

sites:
  - name: ASJordi's Website
    url: https://asjordi.dev
    assignees:
      - ASJordi

  - name: ASJordi's Website v2
    url: https://personal-website-asjordi.web.app/
    assignees:
      - ASJordi

  - name: ASJordi's Links
    url: https://asjordi.link
    assignees:
      - ASJordi

  - name: URL Shortener
    url: https://link-shortly.netlify.app
    assignees:
      - ASJordi

  - name: Weather App
    url: https://weather-app-nodejs.netlify.app
    assignees:
      - ASJordi

  - name: API Words
    url: https://api-words.up.railway.app
    assignees:
      - ASJordi

status-website:
  baseUrl: /website-activity-status
  name: Website Activity Status
  introMessage: Status page which uses real-time data from our GitHub repository. No server required — just GitHub Actions, Issues, and Pages.
  navbar:
    - title: Live Status
      href: https://asjordi.github.io/website-activity-status
    - title: GitHub Repo
      href: https://github.com/$OWNER/$REPO
  theme: night
  logoUrl: https://raw.githubusercontent.com/ASJordi/website-activity-status/master/assets/status.png
  favicon: https://raw.githubusercontent.com/ASJordi/website-activity-status/master/assets/status.png
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration